In [99]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

In [100]:
df=pd.read_csv('updatedclassifier.csv')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4888 entries, 0 to 4887
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Unnamed: 0              4888 non-null   int64
 1   ProdTaken               4888 non-null   int64
 2   Age                     4888 non-null   float64
 3   TypeofContact           4888 non-null   str
 4   CityTier                4888 non-null   int64
 5   DurationOfPitch         4888 non-null   float64
 6   Occupation              4888 non-null   str
 7   Gender                  4888 non-null   str
 8   NumberOfFollowups       4888 non-null   float64
 9   ProductPitched          4888 non-null   str
 10  PreferredPropertyStar   4888 non-null   float64
 11  MaritalStatus           4888 non-null   str
 12  NumberOfTrips           4888 non-null   float64
 13  Passport                4888 non-null   int64
 14  PitchSatisfactionScore  4888 non-null   int64
 15  OwnCar                  4888 non-null   int64
 16  Designation             4888 non-null   str
 17  MonthlyIncome           4888 non-null   float64
 18  TotalVisiting           4888 non-null   float64
dtypes: float64(7), int64(6), str(6)
memory usage: 970.0 KB

In [101]:
df=df.drop('Unnamed: 0', axis=1)

In [102]:
df.head()

,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,Designation,MonthlyIncome,TotalVisiting
0,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3.0,Deluxe,3.0,Unmarried,1.0,1,2,1,Manager,20993.0,3.0
1,0,49.0,Company Invited,1,14.0,Salaried,Male,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,Manager,20130.0,5.0
2,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,4.0,Basic,3.0,Unmarried,7.0,1,3,0,Executive,17090.0,3.0
3,0,33.0,Company Invited,1,9.0,Salaried,Female,3.0,Basic,3.0,Divorced,2.0,1,5,1,Executive,17909.0,3.0
4,0,36.0,Self Enquiry,1,8.0,Small Business,Male,3.0,Basic,4.0,Divorced,1.0,0,5,1,Executive,18468.0,2.0

In [103]:
x=df.drop('ProdTaken',axis=1)
y=df['ProdTaken']

In [104]:
num_feature=x.select_dtypes(exclude='str').columns
cat_feature=x.select_dtypes(include='str').columns

In [105]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
num_transformer=StandardScaler()
cat_transformer=OneHotEncoder()

In [106]:
preprocessor=ColumnTransformer(
    [
        ("StandardScaler", num_transformer, num_feature),
        ("OneHotEncoder", cat_transformer, cat_feature)
    ]
)
x=preprocessor.fit_transform(x)

In [107]:
x

array([[ 0.3792611 ,  1.46836869, -1.12598612, ...,  1.        ,
         0.        ,  0.        ],
       [ 1.25800887, -0.71387094, -0.16390595, ...,  1.        ,
         0.        ,  0.        ],
       [-0.06011278, -0.71387094, -0.88546608, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 1.58753928,  1.46836869,  0.19687412, ...,  0.        ,
         1.        ,  0.        ],
       [-2.03729526,  1.46836869,  0.0766141 , ...,  0.        ,
         0.        ,  0.        ],
       [-0.16995625, -0.71387094, -0.16390595, ...,  0.        ,
         0.        ,  0.        ]], shape=(4888, 32))

In [108]:
from sklearn.model_selection import train_test_split
x_train,x_test, y_train,y_test=train_test_split(x,y, test_size=0.3, random_state=42)

In [109]:
pd.DataFrame(x_train)

,0,1,2,3,4,5,6,7,8,9,...,22,23,24,25,26,27,28,29,30,31
0,1.148165,-0.713871,-0.644946,0.289401,-0.725222,-1.223399,-0.640524,1.407276,0.782392,0.464080,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
1,-0.829017,-0.713871,-0.524686,-0.712434,1.784431,1.519961,-0.640524,1.407276,-1.278132,-1.018613,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
2,-0.938861,-0.713871,-0.163906,1.291235,1.784431,-0.674727,1.561221,-0.057226,0.782392,-1.224992,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,-0.938861,1.468369,-0.765206,0.289401,0.529604,-0.126055,1.561221,-0.057226,0.782392,-0.019436,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
4,-0.389643,-0.713871,-0.524686,1.291235,0.529604,2.617304,-0.640524,0.675025,-1.278132,-0.429720,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3416,-1.048704,-0.713871,-0.644946,1.291235,-0.725222,-0.674727,-0.640524,-1.521728,0.782392,-0.539472,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
3417,0.379261,1.468369,-0.885466,-0.712434,1.784431,-1.223399,-0.640524,1.407276,0.782392,1.528500,...,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3418,0.049731,1.468369,1.519734,0.289401,-0.725222,2.068633,-0.640524,-0.789477,0.782392,-0.362956,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3419,-1.048704,1.468369,1.760254,1.291235,-0.725222,-0.126055,-0.640524,-1.521728,0.782392,-0.255107,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
3420,-1.707765,-0.713871,-0.765206,0.289401,-0.725222,-1.223399,1.561221,-0.057226,-1.278132,-1.085377,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [110]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from xgboost import XGBClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [111]:
models={
    "XGBoost": XGBClassifier(),
    "LogisticRegressiin": LogisticRegression(),
    "GradientBoostingClassifier":GradientBoostingClassifier(),
    "DecisionTreeClassifier":DecisionTreeClassifier(),
    "AdaBoostClassifier":AdaBoostClassifier(),
    "RandomForestClassifier":RandomForestClassifier()
 
}
for i in range(len(list(models))):
    model=list(models.values())[i]
    model.fit(x_train,y_train)

In [112]:
y_train_pred=model.predict(x_train)
y_test_pred=model.predict(x_test)

In [113]:
print(accuracy_score(y_train, y_train_pred))
print(classification_report(y_train, y_train_pred))
print(confusion_matrix(y_train,y_train_pred))

1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      2775
           1       1.00      1.00      1.00       646

    accuracy                           1.00      3421
   macro avg       1.00      1.00      1.00      3421
weighted avg       1.00      1.00      1.00      3421

[[2775    0]
 [   0  646]]

In [114]:
print(accuracy_score(y_test, y_test_pred))
print(classification_report(y_test, y_test_pred))
print(confusion_matrix(y_test,y_test_pred))

0.9195637355146558
              precision    recall  f1-score   support

           0       0.92      0.99      0.95      1193
           1       0.94      0.61      0.74       274

    accuracy                           0.92      1467
   macro avg       0.93      0.80      0.85      1467
weighted avg       0.92      0.92      0.91      1467

[[1183   10]
 [ 108  166]]

In [117]:
from sklearn.model_selection import RandomizedSearchCV
rf_params={
    "max_depth":[5,8,15,None, 10],
    "max_features":[3,5,8,'auto', 10],
    "min_samples_split":[2,8,15,20],
    "n_estimators":[40,50,60,70,80,90]
    }
xgboost_param={
    "learning_rate":[0.1,0.01],
    "max_depth":[5,8,None, 10,15],
    "n-estimators":[100,200,300],
    "colsample_bytree":[0.5,0.8,1,0.3,0.4]
}
randomcv_model=[
    ("RF", RandomForestClassifier(),rf_params),
    ("XGB", XGBClassifier(),xgboost_param)
]

In [118]:
for name,model,param in randomcv_model:
    random=RandomizedSearchCV(estimator=model,
                              param_distributions=param,
                              n_iter=300,
                              cv=3,
                              verbose=2,
                              n_jobs=-1)
    random.fit(x_train,y_train)

Fitting 3 folds for each of 300 candidates, totalling 900 fits

c:\Users\DELL\Desktop\python practice set\.venv\Lib\site-packages\sklearn\model_selection\_validation.py:489: FitFailedWarning:
183 fits failed out of a total of 900.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
92 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\DELL\Desktop\python practice set\.venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 851, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\DELL\Desktop\python practice set\.venv\Lib\site-packages\sklearn\base.py", line 1393, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "c:\Users\DELL\Desktop\python practice set\.venv\Lib\site-packages\sklearn\base.py", line 554, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "c:\Users\DELL\Desktop\python practice set\.venv\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
91 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\DELL\Desktop\python practice set\.venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 851, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\DELL\Desktop\python practice set\.venv\Lib\site-packages\sklearn\base.py", line 1393, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "c:\Users\DELL\Desktop\python practice set\.venv\Lib\site-packages\sklearn\base.py", line 554, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "c:\Users\DELL\Desktop\python practice set\.venv\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
c:\Users\DELL\Desktop\python practice set\.venv\Lib\site-packages\sklearn\model_selection\_search.py:1234: UserWarning: One or more of the test scores are non-finite: [       nan 0.82286006 0.89506204 0.8561834  0.88599797 0.87459933
 0.84595333 0.84565965 0.85910559 0.84069145 0.86553808 0.88044446
 0.83484452 0.84799729        nan 0.83922895 0.86378292 0.86056834
 0.86582894 0.86816709 0.86758358 0.86729144 0.84829149        nan
 0.90178437 0.9006158  0.85939773 0.86670613        nan 0.86962985
        nan 0.87518566 0.85998432 0.86495277 0.86027569 0.83747508
 0.8845388         nan 0.85296754 0.84332124 0.8927244  0.90032212
        nan 0.8412765         nan 0.88716679 0.86641502 0.86202931
 0.89798346 0.87138219 0.88424487 0.85355413 0.88278493 0.86904352
 0.90236788 0.86904403 0.86699827        nan 0.84887628 0.82110568
 0.86027518 0.86611903 0.85092281 0.86641476        nan 0.85998304
 0.82227501 0.82139731        nan 0.84332201 0.86933771        nan
 0.87255255 0.8789835         nan 0.84244507 0.85121367        nan
        nan 0.85910661        nan 0.8857066  0.89067633 0.88161303
 0.83338254 0.87459728 0.82227373 0.85472218 0.86582868 0.83162866
        nan 0.85822993        nan 0.8640766  0.90061555 0.88512257
 0.8415689  0.86115339        nan 0.85559861        nan        nan
 0.84419894 0.83572069        nan 0.8567664         nan        nan
 0.89067685 0.83806064 0.85589177        nan 0.86582919 0.89038496
 0.84770592        nan 0.8836611         nan 0.8751831         nan
        nan 0.86495098 0.85004562 0.85472141 0.88395247        nan
        nan 0.8593985  0.8462447  0.84098334 0.84069043 0.86641296
 0.84215267        nan        nan 0.82169022 0.85150607 0.87372111
        nan        nan 0.85852258 0.83367545 0.84127574 0.85676948
 0.88365879 0.89067659 0.85939875 0.86319967 0.8678747  0.8591061
 0.84244609 0.84156788 0.85822993        nan 0.85910559 0.85092204
 0.8778134  0.86261436 0.86115263 0.86202956 0.86203084 0.89330766
 0.90324584 0.85092127        nan 0.87722912        nan 0.82227424
        nan        nan 0.90236916 0.83455213 0.8819062  0.85092204
 0.85998278 0.88161303 0.84829174 0.87079842        nan 0.87430693
 0.84858414 0.84361466 0.84507485 0.86407378 0.84127574 0.84069068
        nan        nan 0.86612057 0.85939824 0.84712164 0.8468295
 0.89038342 0.86056706 0.87547627 0.83192055 0.85793984 0.84770669
 0.86524517 0.8880445  0.84069197 0.83776773 0.88278493        nan
 0.8503375  0.87810605 0.86962729 0.90178386 0.86202854 0.86378318
 0.83630626 0.87869162 0.85179821 0.85793728 0.84390706 0.85004485
 0.89330842 0.85472141 0.84332252 0.82169047 0.83309039 0.88541318
 0.84361364        nan 0.84449032        nan 0.85267514 0.87079816
 0.87985839 0.87255152 0.86202674 0.89126215 0.85618263 0.852383
 0.88541394 0.8748907  0.84156813 0.83104412 0.84156813        nan
 0.89389245 0.84682822        nan        nan 0.84946031 0.8298753
        nan 0.84069017 0.82052114 0.88307399 0.84244507 0.84565837
 0.83630498 0.86699904 0.88219936 0.83893681 0.82958188 0.84098411
 0.85939875 0.86612005        nan 0.85823019 0.84010717        nan
 0.89447853 0.85589049        nan        nan 0.88628857        nan
 0.83893655 0.85793574        nan 0.85033904 0.86231991 0.86290573
 0.86290317 0.86349129 0.84419869 0.86612287 0.87138244        nan
 0.9009082  0.84449057 0.86378292 0.85998304        nan        nan
 0.87167535 0.85939696 0.90236968        nan 0.83864493 0.84010717
 0.86203008 0.87518182 0.90149146 0.86027466        nan 0.8605686 ]
  warnings.warn(
c:\Users\DELL\Desktop\python practice set\.venv\Lib\site-packages\sklearn\model_selection\_search.py:326: UserWarning: The total space of parameters 150 is smaller than n_iter=300. Running 150 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(

Fitting 3 folds for each of 150 candidates, totalling 450 fits

In [119]:
print(accuracy_score(y_train, y_train_pred))
print(classification_report(y_train, y_train_pred))
print(confusion_matrix(y_train,y_train_pred))

1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      2775
           1       1.00      1.00      1.00       646

    accuracy                           1.00      3421
   macro avg       1.00      1.00      1.00      3421
weighted avg       1.00      1.00      1.00      3421

[[2775    0]
 [   0  646]]

In [120]:
print(accuracy_score(y_test, y_test_pred))
print(classification_report(y_test, y_test_pred))
print(confusion_matrix(y_test,y_test_pred))

0.9195637355146558
              precision    recall  f1-score   support

           0       0.92      0.99      0.95      1193
           1       0.94      0.61      0.74       274

    accuracy                           0.92      1467
   macro avg       0.93      0.80      0.85      1467
weighted avg       0.92      0.92      0.91      1467

[[1183   10]
 [ 108  166]]