In [2]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

In [3]:
df=pd.read_csv('car_price_prediction_.csv')
df.head()

,Car ID,Brand,Year,Engine Size,Fuel Type,Transmission,Mileage,Condition,Price,Model
0,1,Tesla,2016,2.3,Petrol,Manual,114832,New,26613.92,Model X
1,2,BMW,2018,4.4,Electric,Manual,143190,Used,14679.61,5 Series
2,3,Audi,2013,4.5,Electric,Manual,181601,New,44402.61,A4
3,4,Tesla,2011,4.1,Diesel,Automatic,68682,New,86374.33,Model Y
4,5,Ford,2009,2.6,Diesel,Manual,223009,Like New,73577.10,Mustang

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Car ID        2500 non-null   int64
 1   Brand         2500 non-null   str
 2   Year          2500 non-null   int64
 3   Engine Size   2500 non-null   float64
 4   Fuel Type     2500 non-null   str
 5   Transmission  2500 non-null   str
 6   Mileage       2500 non-null   int64
 7   Condition     2500 non-null   str
 8   Price         2500 non-null   float64
 9   Model         2500 non-null   str
dtypes: float64(2), int64(3), str(5)
memory usage: 266.2 KB

In [5]:
df=df.drop('Car ID', axis=1)

In [6]:
df.to_csv('cleaned_regression.csv')

In [7]:
x=df.drop('Price', axis=1)
y=df['Price']

In [8]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x['Model']=le.fit_transform(x['Model'])

In [9]:
num_feature=x.select_dtypes(exclude='str').columns 
cat_feature=x.select_dtypes(include='str').columns

In [10]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer

In [11]:
numeric_transformer=StandardScaler()
cat_transformer=OneHotEncoder()
preprocessor=ColumnTransformer(
    [
        ('OneHotEncoder', cat_transformer, cat_feature),
        ('StandardScaler', numeric_transformer, num_feature)
    ], remainder='passthrough'
)
x=preprocessor.fit_transform(x)
x=pd.DataFrame(x)

In [12]:
x

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.625610,-0.813848,-0.397234,0.708782
1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.911720,0.652872,-0.074626,-1.512177
2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.196444,0.722716,0.362347,-1.265404
3,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,-0.089667,0.443340,-0.922249,0.832169
4,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,-0.375778,-0.604316,0.833415,0.955555
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2495,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.197831,-0.744004,-1.445921,1.202328
2496,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,-1.520220,1.560841,-0.819646,-1.388790
2497,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.340886,-1.651973,1.400157,-0.154924
2498,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,-1.377165,0.722716,0.903436,1.202328
2499,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,-0.947999,0.792559,-0.782366,1.449102

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y, test_size=0.2, random_state=42)

In [14]:
from sklearn.ensemble import AdaBoostRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

In [15]:
models={
    "AdaBoostRegressor": AdaBoostRegressor(),
    "RandomForestRegressor":RandomForestRegressor(),
    "DecisionTreeRegressor": DecisionTreeRegressor(),
    "KNeighborsRegressor":KNeighborsRegressor(),
    "LinearRegression": LinearRegression()
}

In [16]:
for i in range(len(list(models))):
    model=list(models.values())[i]
    model.fit(x_train, y_train)

In [17]:
y_train_pred=model.predict(x_train)
y_test_pred=model.predict(x_test)

In [18]:
print(r2_score(y_train,y_train_pred))
print(mean_absolute_error(y_train, y_train_pred))
print(mean_squared_error(y_train, y_train_pred))
print(np.sqrt(mean_absolute_error(y_train,y_train_pred)))

0.00806068095978818
23546.553216953664
735435538.3088719
153.44886189527006

In [19]:
print(r2_score(y_test,y_test_pred))
print(mean_absolute_error(y_test, y_test_pred))
print(mean_squared_error(y_test, y_test_pred))
print(np.sqrt(mean_absolute_error(y_test,y_test_pred)))

-0.0023865136561600497
23688.742504465914
759361243.6566817
153.91147619481114

In [20]:
rf_param={
    "max_depth":[2,8,5,None,20],
    "max_features":[5,7,'auto',9],
    "min_samples_split":[2,8,15,20],
    "n_estimators":[100,200,500,1000]
}
adaboost_param={
    "n_estimators":[50,60,70,80,90],
    "learning_rate": [0.01, 0.1, 0.5, 1.0]
}

In [21]:
from sklearn.model_selection import RandomizedSearchCV
randomcv=[
        ("RF", RandomForestRegressor(), rf_param),
        ("AB", AdaBoostRegressor(), adaboost_param)
    ]

In [22]:
model_param={}
for name, model, params in randomcv:
    random=RandomizedSearchCV(estimator=model,
                              param_distributions=params,
                              cv=3,
                              n_iter=100,
                              verbose=2,
                              n_jobs=-1)
    random.fit(x_train,y_train)

Fitting 3 folds for each of 100 candidates, totalling 300 fits

KeyboardInterrupt:

In [ ]:
y_train_pred=random.predict(x_train)
y_test_pred=random.predict(x_test)

In [ ]:
print(r2_score(y_train,y_train_pred))
print(mean_absolute_error(y_train, y_train_pred))
print(mean_squared_error(y_train, y_train_pred))
print(np.sqrt(mean_absolute_error(y_train,y_train_pred)))

0.022664470904395384
23417.30885305691
724608115.7910771
153.02715070554282

In [ ]:
print(r2_score(y_test, y_test_pred))
print(mean_absolute_error(y_test, y_test_pred))
print(mean_squared_error(y_test, y_test_pred))

0.005853125905927126
23658.99785968776
753119277.2496041